name: Chrome Web Store Publishing

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version to publish'
        required: true
        type: string

permissions:
  contents: read

jobs:
  publish-extension:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build extension
      run: npm run build:extension

    - name: Update manifest version
      run: |
        VERSION="${{ github.event.inputs.version || github.event.release.tag_name }}"
        VERSION="${VERSION#v}"  # Remove 'v' prefix if present
        
        # Update version in manifest.json
        jq ".version = \"$VERSION\"" dist/extension/manifest.json > dist/extension/manifest.json.tmp
        mv dist/extension/manifest.json.tmp dist/extension/manifest.json
        
        echo "Updated manifest version to: $VERSION"

    - name: Create extension package
      run: |
        cd dist/extension
        zip -r ../../bookmarkdown-extension.zip .
        cd ../..

    - name: Upload to Chrome Web Store
      uses: mobilefirst/cws-publish@latest
      with:
        action: 'upload'
        client_id: ${{ secrets.CHROME_CLIENT_ID }}
        client_secret: ${{ secrets.CHROME_CLIENT_SECRET }}
        refresh_token: ${{ secrets.CHROME_REFRESH_TOKEN }}
        extension_id: ${{ secrets.CHROME_EXTENSION_ID }}
        zip_file: 'bookmarkdown-extension.zip'

    - name: Publish to Chrome Web Store
      uses: mobilefirst/cws-publish@latest
      with:
        action: 'publish'
        client_id: ${{ secrets.CHROME_CLIENT_ID }}
        client_secret: ${{ secrets.CHROME_CLIENT_SECRET }}
        refresh_token: ${{ secrets.CHROME_REFRESH_TOKEN }}
        extension_id: ${{ secrets.CHROME_EXTENSION_ID }}

    - name: Notify publication success
      if: success()
      run: |
        echo "🎉 Chrome extension published successfully!"
        echo "Extension ID: ${{ secrets.CHROME_EXTENSION_ID }}"
        echo "Version: ${{ github.event.inputs.version || github.event.release.tag_name }}"

    - name: Upload extension artifact
      uses: actions/upload-artifact@v4
      with:
        name: published-extension
        path: bookmarkdown-extension.zip
        retention-days: 90