# Cloudflare Worker configuration for BookMarkDown Web Application
name = "bookmarkdown-web"
main = "src/worker.ts"
compatibility_date = "2024-01-15"

# Custom domain configuration
routes = [
  { pattern = "bookmarkdown.ar90n.net/*", zone_name = "ar90n.net" }
]

# Static assets configuration
[assets]
directory = "../dist/web"
binding = "ASSETS"

# Environment variables
[vars]
ENVIRONMENT = "production"