# Cloudflare Worker configuration for BookMarkDown Web Application
name = "bookmarkdown-web"
main = "src/worker.ts"
compatibility_date = "2024-01-15"

# Static assets configuration
[assets]
directory = "../dist/web"
binding = "ASSETS"

# Custom domain configuration (disabled temporarily)
# routes = [
#   { pattern = "bookmarkdown.ar90n.net", custom_domain = true }
# ]

# Environment variables
[vars]
ENVIRONMENT = "production"